In [4]:
import numpy as np

In [14]:
def generate_grid(n:int, m: int):
    
    grid = np.zeros((n,m))
    
    grid[0][3] = +1
    grid[1][3] = -1
    
    return grid
    

In [6]:
n, m = 3, 4

In [15]:
generate_grid(n, m)

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
# start point
x0, y0 = 2, 0

In [18]:
from enum import Enum
 
class Action(Enum):
    TOP = 1
    BOTTOM = 2
    RIGHT = 3
    LEFT = 4

In [21]:
# Si l'action est d'aller a TOP: on a donc on a une proba de 0.8 d'aller a top et 0.1 pour les deux autres direction a 90 degree
# a savoir RIGHT LEFT.

# Si l'action est d'aller a Right alors on a une proba de 0.8 d'y aller et de 0.1 pour les deux autres directions a 90 degree 
# a savoir, TOP et Bottom

In [22]:
rewards = np.zeros((n,m))
rewards[0][3] = +1
rewards[1][3] = -1

In [23]:
rewards

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
value_function = np.zeros((n,m))

In [ ]:
def proba_transition(action):
    

In [29]:
rewards

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.]])

In [30]:
def get_possible_directions(x, y, n_row = 3, n_col=4):
    
    if x == 0 and y == 0:
        return ['B', 'R']
    
    if x == 0 and y == n_col -1:
        return ['B', 'L']
    
    if x == 0 and 0 < y < n_col:
        return ['B', 'R', 'L']
    
    if x == n_row - 1 and y == 0:
        return ['T', 'R']
    
    if x == n_row - 1 and y == n_col -1:
        return ['T', 'L']
    
    if x == n_row - 1 and 0 < y < n_col:
        return ['T', 'R', 'L']
    
    if y == 0 and 0 < x < n_row:
        return ['T', 'B', 'R']
    
    if y == n_col - 1 and 0 < x < n_row:
        return ['T', 'B', 'L']
    
    if 0 < x < n_row and 0 < y < n_col:
        return ['T', 'B', 'R', 'L']
    

In [ ]:
import random

def get_next_position(x, y, action, invalid_cell):
    
    possible_directions = get_possible_actions(x,y) # possible action in this state
    
    if action in possible_directions:
        
        if 0 < x < n_row and 0 < y < n_col:
            if action == 'T' or action == 'B':
                realisable_directions = ['R', 'L']
            else:
                realisable_directions = ['B', 'T']
            
        else:
            realisable_directions = [direction for direction in possibles_directions if direction != action ]
            
            
        return realisable_directions  

In [26]:
n_iter = 0
ITER_MAX = 1000
x0, y0 = 0, 0
γ = 0.9

V = np.zeros((n,m))
V[0][3] = +1
V[1][3] = -1


while n_iter < ITER_MAX:
    
    for x in range(n_row):
        for y in range(n_col):
            
            V[x][x] =  
    

SyntaxError: incomplete input (1137679079.py, line 6)